import 'server-only';
import { drizzle } from 'drizzle-orm/postgres-js';
import postgres from 'postgres';
import {
  organizations,
  workspaces,
  installations,
  users,
  watchedConversations,
  threadParticipants,
  userStylePreferences,
  messageEmbeddings,
  refinementFeedback,
  gdprConsent,
  personContext,
  conversationContext,
  reportSettings,
  googleIntegrations,
  workflowConfig,
  suggestionFeedback,
  auditLogs,
  autoRespondLog,
  userSubscriptions,
  usageRecords,
  usageEvents,
  coupons,
  couponRedemptions,
  referrals,
  referralEvents,
  actionableItems,
  clientProfiles,
  clientContacts,
  brandVoiceTemplates,
  knowledgeBaseDocuments,
  escalationAlerts,
  orgStyleSettings,
  responseTemplates,
  guardrailConfig,
  guardrailViolations,
  emailSubscribers,
  suggestionMetrics,
  topicClassifications,
  communicationTrends,
  kbCandidates,
  kbEffectiveness,
  satisfactionSurveys,
  communicationHealthScores,
} from '@slack-speak/database';

const connectionString = process.env.DATABASE_URL || '';
const isProduction = process.env.NODE_ENV === 'production';

// Use postgres.js to match the database package
const queryClient = postgres(connectionString, {
  max: 10,
  idle_timeout: 20,
  connect_timeout: 10,
  ssl: isProduction ? { rejectUnauthorized: false } : false,
});

// Create schema object explicitly for proper type inference
const schema = {
  organizations,
  workspaces,
  installations,
  users,
  watchedConversations,
  threadParticipants,
  userStylePreferences,
  messageEmbeddings,
  refinementFeedback,
  gdprConsent,
  personContext,
  conversationContext,
  reportSettings,
  googleIntegrations,
  workflowConfig,
  suggestionFeedback,
  auditLogs,
  autoRespondLog,
  userSubscriptions,
  usageRecords,
  usageEvents,
  coupons,
  couponRedemptions,
  referrals,
  referralEvents,
  actionableItems,
  clientProfiles,
  clientContacts,
  brandVoiceTemplates,
  knowledgeBaseDocuments,
  escalationAlerts,
  orgStyleSettings,
  responseTemplates,
  guardrailConfig,
  guardrailViolations,
  emailSubscribers,
  suggestionMetrics,
  topicClassifications,
  communicationTrends,
  kbCandidates,
  kbEffectiveness,
  satisfactionSurveys,
  communicationHealthScores,
};

export const db = drizzle(queryClient, { schema });

// Re-export schema for consistent type usage
export { schema };

// Re-export types from database package
export type {
  ClientProfile,
  NewClientProfile,
  ClientContact,
  NewClientContact,
  BrandVoiceTemplate,
  NewBrandVoiceTemplate,
  KnowledgeBaseDocument,
  NewKnowledgeBaseDocument,
  EscalationAlert,
  NewEscalationAlert,
  OrgStyleSettings,
  NewOrgStyleSettings,
  ResponseTemplate,
  NewResponseTemplate,
  GuardrailConfig,
  NewGuardrailConfig,
  GuardrailViolation,
  NewGuardrailViolation,
  SuggestionMetric,
  NewSuggestionMetric,
  KbCandidate,
  NewKbCandidate,
  KbEffectiveness,
  NewKbEffectiveness,
  SatisfactionSurvey,
  NewSatisfactionSurvey,
  CommunicationHealthScore,
  NewCommunicationHealthScore,
} from '@slack-speak/database';
