# DigitalOcean App Platform Specification
# Deploy: doctl apps create --spec app.yaml
# Update: doctl apps update <app-id> --spec app.yaml
#
# See .planning/DIGITALOCEAN-DEPLOYMENT.md for full setup guide

name: slack-speak-for-me
region: nyc

# Alerts
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED

# ============================================
# Services
# ============================================
services:
  # --------------------------------------------
  # Slack Backend Service
  # --------------------------------------------
  - name: slack-backend
    dockerfile_path: apps/slack-backend/Dockerfile
    github:
      repo: chrisbartolo/slack-speak-for-me  
      branch: main
      deploy_on_push: true

    instance_count: 1
    instance_size_slug: basic-xxs  # $5/mo - scale up as needed

    http_port: 3000

    health_check:
      http_path: /health/live
      initial_delay_seconds: 10
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3

    # Backend handles Slack events, OAuth, health, and API
    routes:
      - path: /slack
      - path: /oauth
      - path: /health
      - path: /api

    envs:
      # Database (from managed database)
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET

      # Redis
      - key: REDIS_HOST
        scope: RUN_TIME
        type: SECRET
      - key: REDIS_PORT
        scope: RUN_TIME
        value: "25061"

      # Slack OAuth
      - key: SLACK_CLIENT_ID
        scope: RUN_TIME
        type: SECRET
      - key: SLACK_CLIENT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: SLACK_SIGNING_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: SLACK_STATE_SECRET
        scope: RUN_TIME
        type: SECRET

      # Google OAuth
      - key: GOOGLE_CLIENT_ID
        scope: RUN_TIME
        type: SECRET
      - key: GOOGLE_CLIENT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: GOOGLE_REDIRECT_URI
        scope: RUN_TIME
        value: ${slack-backend.PUBLIC_URL}/oauth/google/callback

      # Encryption
      - key: ENCRYPTION_KEY
        scope: RUN_TIME
        type: SECRET

      # Anthropic AI
      - key: ANTHROPIC_API_KEY
        scope: RUN_TIME
        type: SECRET

      # App Config
      - key: NODE_ENV
        scope: RUN_TIME
        value: production
      - key: PORT
        scope: RUN_TIME
        value: "3000"
      - key: WEB_PORTAL_URL
        scope: RUN_TIME
        value: ${web-portal.PUBLIC_URL}

  # --------------------------------------------
  # Web Portal Service (Next.js)
  # --------------------------------------------
  - name: web-portal
    dockerfile_path: apps/web-portal/Dockerfile
    github:
      repo: chrisbartolo/slack-speak-for-me 
      branch: main
      deploy_on_push: true

    instance_count: 1
    instance_size_slug: basic-xxs  # $5/mo - scale up as needed

    http_port: 3001

    health_check:
      http_path: /api/health
      initial_delay_seconds: 10
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3

    # Web portal serves the landing page and dashboard
    routes:
      - path: /

    envs:
      # Database (same as slack-backend)
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET

      # Slack OAuth (for user login)
      - key: SLACK_CLIENT_ID
        scope: RUN_TIME
        type: SECRET
      - key: SLACK_CLIENT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: SLACK_WEB_REDIRECT_URI
        scope: RUN_TIME
        value: ${web-portal.PUBLIC_URL}/callback

      # Session
      - key: SESSION_SECRET
        scope: RUN_TIME
        type: SECRET

      # Next.js Config
      - key: NODE_ENV
        scope: RUN_TIME
        value: production
      - key: NEXTAUTH_URL
        scope: RUN_TIME
        value: ${web-portal.PUBLIC_URL}

# ============================================
# Jobs (Database migrations)
# ============================================
jobs:
  - name: db-migrate
    dockerfile_path: apps/slack-backend/Dockerfile
    github:
      repo: chrisbartolo/slack-speak-for-me
      branch: main
    instance_size_slug: basic-xxs
    kind: PRE_DEPLOY
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
    run_command: sh -c "cd packages/database && npx drizzle-kit push"

# ============================================
# Databases
# ============================================
databases:
  - name: db
    engine: PG
    version: "16"
    size: db-s-1vcpu-1gb  # $15/mo - smallest managed DB
    num_nodes: 1

# ============================================
# Setup Notes
# ============================================
#
# 1. REDIS:
#    Create managed Redis separately in DigitalOcean dashboard.
#    Set REDIS_HOST to the Redis hostname manually.
#
# 2. PGVECTOR:
#    After database creation, connect and run:
#    CREATE EXTENSION IF NOT EXISTS vector;
#
# 3. SECRETS TO CONFIGURE:
#    Generate secrets with: openssl rand -hex 32
#    - SLACK_STATE_SECRET (32+ chars)
#    - ENCRYPTION_KEY (64 hex chars = 32 bytes)
#    - SESSION_SECRET (32 chars)
#
# 4. AFTER DEPLOY:
#    Update Slack App settings with your DO app URL:
#    - OAuth Redirect: https://YOUR_APP.ondigitalocean.app/slack/oauth_redirect
#    - Events URL: https://YOUR_APP.ondigitalocean.app/slack/events
#    - Commands URL: https://YOUR_APP.ondigitalocean.app/slack/events
