import { requireAdmin } from '@/lib/auth/admin';
import { getTeamMetrics, getAdoptionTrend, getUserMetrics, getActionBreakdown } from '@/lib/admin/analytics';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { AdoptionTrendChart, ActionBreakdownChart, UserMetricsTable } from '@/components/admin/analytics-charts';
import { TrendingUp, TrendingDown, Minus, Download } from 'lucide-react';

export default async function AnalyticsPage() {
  const session = await requireAdmin();

  if (!session.organizationId) {
    return (
      <div className="p-6">
        <p className="text-muted-foreground">No organization found</p>
      </div>
    );
  }

  // Fetch all analytics data
  let teamMetrics, adoptionTrend, userMetrics, actionBreakdown;
  try {
    [teamMetrics, adoptionTrend, userMetrics, actionBreakdown] = await Promise.all([
      getTeamMetrics(session.organizationId!, session.workspaceId),
      getAdoptionTrend(session.organizationId!, session.workspaceId, 6),
      getUserMetrics(session.organizationId!, session.workspaceId),
      getActionBreakdown(session.organizationId!, session.workspaceId),
    ]);
  } catch (error) {
    console.error('Failed to fetch analytics data:', error);
    return (
      <div className="p-6 space-y-6">
        <h1 className="text-3xl font-bold">Team Analytics</h1>
        <p className="text-muted-foreground">
          No analytics data available yet. Analytics will appear once team members start using Speak for Me.
        </p>
      </div>
    );
  }

  // Format time saved
  const hours = Math.floor(teamMetrics.estimatedTimeSavedMinutes / 60);
  const minutes = teamMetrics.estimatedTimeSavedMinutes % 60;
  const timeSavedFormatted = hours > 0
    ? `${hours}h ${minutes}m`
    : `${minutes}m`;

  // Helper to get trend indicator
  const getTrendColor = (rate: number, thresholdHigh: number, thresholdMid: number) => {
    if (rate >= thresholdHigh) return 'text-emerald-600';
    if (rate >= thresholdMid) return 'text-amber-600';
    return 'text-red-600';
  };

  const getTrendIcon = (rate: number, thresholdHigh: number, thresholdMid: number) => {
    if (rate >= thresholdHigh) return TrendingUp;
    if (rate >= thresholdMid) return Minus;
    return TrendingDown;
  };

  const adoptionColor = getTrendColor(teamMetrics.adoptionRate, 70, 40);
  const adoptionIcon = getTrendIcon(teamMetrics.adoptionRate, 70, 40);

  return (
    <div className="p-6 space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold">Team Analytics</h1>
          <p className="text-muted-foreground mt-1">
            Track adoption, usage, and AI accuracy across your organization
          </p>
        </div>
        <a
          href="/api/admin/analytics?format=csv"
          download
          className="inline-flex items-center gap-2 px-4 py-2 bg-primary text-primary-foreground rounded-lg hover:bg-primary/90 transition-colors"
        >
          <Download className="w-4 h-4" />
          Export CSV
        </a>
      </div>

      {/* Summary Cards */}
      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
        {/* Total Suggestions */}
        <Card>
          <CardHeader className="pb-3">
            <CardDescription>Total Suggestions</CardDescription>
            <CardTitle className="text-3xl">{teamMetrics.totalSuggestions.toLocaleString()}</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-xs text-muted-foreground">
              Generated by {teamMetrics.activeUsers} active users
            </p>
          </CardContent>
        </Card>

        {/* Adoption Rate */}
        <Card>
          <CardHeader className="pb-3">
            <CardDescription>Adoption Rate</CardDescription>
            <CardTitle className="text-3xl flex items-center gap-2">
              {teamMetrics.adoptionRate.toFixed(1)}%
              {(() => {
                const Icon = adoptionIcon;
                return <Icon className={`w-5 h-5 ${adoptionColor}`} />;
              })()}
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className={`text-xs font-medium ${adoptionColor}`}>
              {teamMetrics.activeUsers} of {teamMetrics.totalUsers} users active (last 30 days)
            </p>
          </CardContent>
        </Card>

        {/* AI Accuracy */}
        <Card>
          <CardHeader className="pb-3">
            <CardDescription>AI Accuracy</CardDescription>
            <CardTitle className="text-3xl">{teamMetrics.acceptanceRate.toFixed(1)}%</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-xs text-muted-foreground">
              {teamMetrics.acceptedCount.toLocaleString()} accepted,{' '}
              {teamMetrics.refinedCount.toLocaleString()} refined
            </p>
          </CardContent>
        </Card>

        {/* Time Saved */}
        <Card>
          <CardHeader className="pb-3">
            <CardDescription>Time Saved</CardDescription>
            <CardTitle className="text-3xl">{timeSavedFormatted}</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-xs text-muted-foreground">
              Based on {(teamMetrics.acceptedCount + teamMetrics.refinedCount).toLocaleString()}{' '}
              accepted responses
            </p>
          </CardContent>
        </Card>
      </div>

      {/* Adoption Trend Chart */}
      <AdoptionTrendChart data={adoptionTrend} />

      {/* Action Breakdown and User Metrics */}
      <div className="grid gap-6 lg:grid-cols-2">
        <ActionBreakdownChart data={actionBreakdown} />
        <UserMetricsTable data={userMetrics} />
      </div>
    </div>
  );
}
